insert into products (name, brand, category, price, description, image_file_name, time_created) values 
('Samsung Galaxy S23 Ultra 5G 512GB', 'Samsung', 'Phone', '25990000', 'Samsung Galaxy S23 Ultra 5G 512GB là một sản phẩm công nghệ không còn xa lạ với những người yêu công nghệ. Máy vừa được giới thiệu với nhiều tính năng và công nghệ nổi bật, đánh dấu một bước tiến đột phá của Samsung trong năm 2023, nhằm tạo nên một thương hiệu hàng đầu trong ngành.', 'samsung-galaxy-s23-ultra-thumb-den-600x600.jpg', current_timestamp),
('Apple Watch SE 2023 GPS 40mm', 'Apple', 'Watches', '6090000', 'Apple Watch SE 2023 GPS 40mm viền nhôm dây thể thao là chiếc smartwatch có mức giá dễ tiếp cận nhất nhà Táo, là lựa chọn tối ưu ngân sách cho người dùng nhưng vẫn đảm bảo một thiết kế đẹp mắt, hỗ trợ đa dạng tính năng cũng như tiện ích hằng ngày.', 'apple-watch-se-2023-40mm-vien-nhom-day-silicone-xanh-duong-thumb-1-600x600.jpg', current_timestamp),
('Camera IP 360 Độ 2MP IMOU Ranger 2C A22EP-L', 'Imou', 'Camera', '550000', 'Camera IP 360 Độ 2MP IMOU Ranger 2C A22EP-L với kiểu dáng nhỏ nhắn, chân đế bằng phẳng giúp dễ dàng đặt trên bàn hay lắp trên các mặt phẳng, camera hỗ trợ ghi lại bao quát không gian xung quanh với độ sắc nét cao, hứa hẹn mang đến người dùng những trải nghiệm tốt nhất.', 'camera-ip-360-do-1080p-imou-ranger-2c-a22ep-l-thumb-600x600.jpg', current_timestamp),
('Điện thoại OPPO Reno10 5G 256GB Xanh', 'Oppo', 'Phone', '10290000', 'Là một trong những chiếc smartphone mới nhất của OPPO trên thị trường hiện nay, OPPO Reno10 5G mang trên mình bộ áo đẹp mắt, hiệu năng ổn định đi cùng với đó là khả năng nhiếp ảnh vượt trội, đáp ứng mượt mà hầu hết các nhu cầu của người dùng.', 'oppo-reno10-blue-thumbnew-600x600.jpg', current_timestamp),
('Laptop Apple MacBook Air 13 inch M1 2020 8-core CPU/8GB/256GB/7-core GPU', 'Apple', 'Laptop', '18490000', 'Laptop Apple MacBook Air M1 2020 thuộc dòng laptop cao cấp sang trọng có cấu hình mạnh mẽ, chinh phục được các tính năng văn phòng lẫn đồ hoạ mà bạn mong muốn, thời lượng pin dài, thiết kế mỏng nhẹ sẽ đáp ứng tốt các nhu cầu làm việc của bạn.', 'macbook-air-m1-2020-gold-600x600.jpg', current_timestamp),
('Đồng hồ MVW 40 mm Nam ML035-01', 'MVW', 'Watch', '490000', 'Sản phẩm đồng hồ mang thương hiệu MVW với nhiều mẫu mã năng động, trẻ trung nhưng không kém phần tinh tế và sang trọng, phù hợp với tất cả mọi người hoạt động ở nhiều lĩnh vực từ dân văn phòng đến doanh nhân.' ,'mww-ml035-01-nam-thumb-fix-600x600.jpg', current_timestamp),
('Điện thoại realme C55 8GB', 'Realme', 'Phone', '4990000', 'realme C55 8GB mẫu điện thoại mới đến từ nhà realme, sở hữu bộ thông số khá ấn tượng. Máy mang trong mình một thiết kế đẹp mắt, hiệu năng ổn định cùng khả năng chụp ảnh chi tiết hứa hẹn sẽ không làm bạn thất vọng.', 'realme-c35-vang-thumb-600x600.jpg', current_timestamp),
('Laptop Asus Vivobook 15 OLED A1505VA i5 13500H/16GB/512GB/Chuột/Win11 (L1341W)', 'Asus', 'Laptop', '16990000', 'Bạn đang tìm kiếm cho mình một mẫu laptop học tập - văn phòng mang hiệu năng xử lý mạnh mẽ, khung hình hiển thị sắc nét cùng đa dạng các tính năng hiện đại. Laptop Asus Vivobook 15 OLED A1505VA i5 13500H (L1341W) là một trong những lựa chọn hàng đầu cho việc đáp ứng hoàn hảo nhu cầu công việc, học tập cũng như giải trí thường ngày.', 'asus-vivobook-15-oled-a1505va-i5-l1341w.jpg', current_timestamp),
('Đồng hồ thông minh BeFit WatchFit 46.7mm', 'BeFit', 'Watch', '540000', 'BeFit WatchFit được trang bị các chức năng sức khỏe và thể thao cơ bản, đáp ứng được nhu cầu sử dụng của người dùng phổ thông. Tuy thuộc phân khúc giá rẻ nhưng chiếc đồng hồ thông minh này vẫn được trang bị tính năng nghe gọi, đảm bảo sự thuận tiện trong quá trình sử dụng.', 'befit-watch-fit-vang-tn-600x600.jpg', current_timestamp),
('Laptop HP 14 ep0126TU i3 N305/8GB/256GB/Win11 (8U233PA)', 'HP', 'Laptop', '8990000', 'Chỉ với mức giá tầm 12 triệu, bạn đã có thể sở hữu ngay cho mình một mẫu laptop học tập - văn phòng đến từ thương hiệu HP, laptop HP 14 ep0126TU i3 N305 (8U233PA) với hiệu năng ổn định, kiểu dáng thời thượng, đáp ứng nhẹ nhàng mọi yêu cầu công việc và giải trí của người dùng.', 'hp-14-ep0126tu-i3-8u233pa.jpg', current_timestamp),
('Loa Bluetooth AVA+ Go Z09', 'AVA+', 'Accessories', '90000', 'Loa Bluetooth AVA+ Go Z09 là phiên bản loa giá rẻ nhưng có thiết kế ấn tượng với ngoại hình nhỏ gọn, đèn LED sống động, đi cùng các tiện ích hiện đại, phục vụ tốt nhu cầu giải trí cơ bản của người dùng.', 'loa-bluetooth-ava-go-z09-tb-600x600.jpg', current_timestamp),
('Điện thoại vivo Y36 256GB', 'Vivo', 'Phone', '5840000', 'vivo Y36, chiếc điện thoại dòng Y được nhà vivo tung ra thị trường Việt Nam vào tháng 06/2023. Máy sở hữu vẻ ngoài hiện đại và trẻ trung, màn hình hiển thị sắc nét cùng một hiệu năng ổn định với các tác vụ hằng ngày.', 'vivo-y36-black-thumbnew-600x600.jpg', current_timestamp);

